services:
  nats:
    image: nats:2.10
    command: ["-js", "-m", "8222", "--store_dir", "/data"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - pix2pi_nats_data:/data

volumes:
  pix2pi_nats_data:
