#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

PREV_REPORT="reports/pilot/faz4c/4c_6g_business_acceptance_gate_report.md"
INPUT_ENV="docs/pilot/faz4c/4c_6g_business_acceptance_input.env"
ACCEPTANCE_FORM="uat/pilot/faz4c/uzmanparcaci/business_acceptance_form.md"
EXECUTION_TEMPLATE="uat/pilot/faz4c/uzmanparcaci/uat_execution_template.md"

DOC_FILE="docs/pilot/faz4c/4c_6g_2_business_acceptance_apply.md"
REPORT_FILE="reports/pilot/faz4c/4c_6g_2_business_acceptance_apply_report.md"

echo "===== 4C-6G-2 BUSINESS ACCEPTANCE APPLY / GATE FINALIZATION ====="

fail() {
  echo "HATA ❌ $1"
  exit 1
}

[ -f "$PREV_REPORT" ] || fail "4C-6G report yok: $PREV_REPORT"
[ -f "$INPUT_ENV" ] || fail "Business acceptance input env yok: $INPUT_ENV"
[ -f "$ACCEPTANCE_FORM" ] || fail "Business acceptance form yok: $ACCEPTANCE_FORM"
[ -f "$EXECUTION_TEMPLATE" ] || fail "UAT execution template yok: $EXECUTION_TEMPLATE"

grep -q "4C_6G_GATE_DOC_STATUS=PASS" "$PREV_REPORT" || fail "4C-6G gate doc PASS degil"
grep -q "4C_6G_TECHNICAL_UAT_STATUS=PASS" "$PREV_REPORT" || fail "4C-6G technical UAT PASS degil"
grep -q "4C_6G_CRITICAL_BLOCKER_COUNT=0" "$PREV_REPORT" || fail "4C-6G critical blocker 0 degil"
grep -q "4C_6G_2_READY=YES" "$PREV_REPORT" || fail "4C-6G-2 ready YES yok"

# shellcheck disable=SC1090
source "$INPUT_ENV"

required_keys=(
  BUSINESS_ACCEPTANCE_STATUS
  BUSINESS_REPRESENTATIVE_NAME
  BUSINESS_ACCEPTANCE_DATE
  BUSINESS_ACCEPTANCE_NOTE
  BUSINESS_ACCEPTS_TENANT_ACCESS
  BUSINESS_ACCEPTS_USER_ROLE_ACCESS
  BUSINESS_ACCEPTS_STAGING_PRODUCTS
  BUSINESS_ACCEPTS_OEM_FIELD
  BUSINESS_ACCEPTS_EQUIVALENT_FIELD
  BUSINESS_ACCEPTS_VEHICLE_FITMENT_FIELD
  BUSINESS_ACCEPTS_BARCODE_NON_BLOCKER
  BUSINESS_ACCEPTS_MARKETPLACE_PHASE_4D
)

PENDING_FIELD_COUNT=0
INVALID_FIELD_COUNT=0
MISSING_FIELD_COUNT=0
MISSING_FIELDS=""
PENDING_FIELDS=""
INVALID_FIELDS=""

for key in "${required_keys[@]}"; do
  val="${!key:-__MISSING__}"

  if [ "$val" = "__MISSING__" ]; then
    MISSING_FIELD_COUNT=$((MISSING_FIELD_COUNT + 1))
    MISSING_FIELDS="${MISSING_FIELDS}${key} "
    continue
  fi

  if [ "$val" = "PENDING" ] || [ -z "$val" ]; then
    PENDING_FIELD_COUNT=$((PENDING_FIELD_COUNT + 1))
    PENDING_FIELDS="${PENDING_FIELDS}${key} "
  fi
done

case "${BUSINESS_ACCEPTANCE_STATUS:-PENDING}" in
  PASS|CONDITIONAL_PASS|FAIL)
    ;;
  *)
    INVALID_FIELD_COUNT=$((INVALID_FIELD_COUNT + 1))
    INVALID_FIELDS="${INVALID_FIELDS}BUSINESS_ACCEPTANCE_STATUS "
    ;;
esac

yes_no_keys=(
  BUSINESS_ACCEPTS_TENANT_ACCESS
  BUSINESS_ACCEPTS_USER_ROLE_ACCESS
  BUSINESS_ACCEPTS_STAGING_PRODUCTS
  BUSINESS_ACCEPTS_OEM_FIELD
  BUSINESS_ACCEPTS_EQUIVALENT_FIELD
  BUSINESS_ACCEPTS_VEHICLE_FITMENT_FIELD
  BUSINESS_ACCEPTS_BARCODE_NON_BLOCKER
  BUSINESS_ACCEPTS_MARKETPLACE_PHASE_4D
)

for key in "${yes_no_keys[@]}"; do
  val="${!key:-PENDING}"

  if [ "$val" = "PENDING" ]; then
    continue
  fi

  case "$val" in
    YES|NO)
      ;;
    *)
      INVALID_FIELD_COUNT=$((INVALID_FIELD_COUNT + 1))
      INVALID_FIELDS="${INVALID_FIELDS}${key} "
      ;;
  esac
done

ACCEPTANCE_APPLY_STATUS="PASS"
BUSINESS_ACCEPTANCE_GATE_STATUS="PASS"
FINAL_UAT_RESULT="PASS"
GO_NO_GO_READY="YES"
NEXT_READY="YES"
BLOCKER_REASON="NONE"
CRITICAL_BLOCKER_COUNT="0"
WARNING_COUNT="${WARNING_COUNT:-2}"

if [ "$MISSING_FIELD_COUNT" -ne 0 ] || [ "$PENDING_FIELD_COUNT" -ne 0 ] || [ "$INVALID_FIELD_COUNT" -ne 0 ]; then
  ACCEPTANCE_APPLY_STATUS="BLOCKED"
  BUSINESS_ACCEPTANCE_GATE_STATUS="PENDING"
  FINAL_UAT_RESULT="PENDING_BUSINESS_ACCEPTANCE"
  GO_NO_GO_READY="NO"
  NEXT_READY="NO"
  BLOCKER_REASON="BUSINESS_ACCEPTANCE_FIELDS_NOT_FINAL"
fi

if [ "${BUSINESS_ACCEPTANCE_STATUS:-PENDING}" = "FAIL" ]; then
  ACCEPTANCE_APPLY_STATUS="FAIL"
  BUSINESS_ACCEPTANCE_GATE_STATUS="FAIL"
  FINAL_UAT_RESULT="FAIL"
  GO_NO_GO_READY="NO"
  NEXT_READY="NO"
  CRITICAL_BLOCKER_COUNT="1"
  BLOCKER_REASON="BUSINESS_ACCEPTANCE_FAIL"
fi

if [ "${BUSINESS_ACCEPTANCE_STATUS:-PENDING}" = "CONDITIONAL_PASS" ] && [ "$ACCEPTANCE_APPLY_STATUS" = "PASS" ]; then
  FINAL_UAT_RESULT="CONDITIONAL_PASS"
  GO_NO_GO_READY="YES"
  NEXT_READY="YES"
fi

if [ "${BUSINESS_ACCEPTANCE_STATUS:-PENDING}" = "PASS" ] && [ "$ACCEPTANCE_APPLY_STATUS" = "PASS" ]; then
  FINAL_UAT_RESULT="PASS"
  GO_NO_GO_READY="YES"
  NEXT_READY="YES"
fi

cat > "$DOC_FILE" <<DOC_EOF
# FAZ 4C — 4C-6G-2 Business Acceptance Apply / Gate Finalization

## Amaç

4C-6G business acceptance input dosyasını okuyup UAT business acceptance gate sonucunu belirlemek.

Bu adım DB'ye yazmaz.

---

## 1. Kaynak dosyalar

INPUT_ENV=$INPUT_ENV
ACCEPTANCE_FORM=$ACCEPTANCE_FORM
PREV_REPORT=$PREV_REPORT

---

## 2. Acceptance input

BUSINESS_ACCEPTANCE_STATUS=${BUSINESS_ACCEPTANCE_STATUS:-PENDING}
BUSINESS_REPRESENTATIVE_NAME=${BUSINESS_REPRESENTATIVE_NAME:-PENDING}
BUSINESS_ACCEPTANCE_DATE=${BUSINESS_ACCEPTANCE_DATE:-PENDING}
BUSINESS_ACCEPTANCE_NOTE=${BUSINESS_ACCEPTANCE_NOTE:-PENDING}

BUSINESS_ACCEPTS_TENANT_ACCESS=${BUSINESS_ACCEPTS_TENANT_ACCESS:-PENDING}
BUSINESS_ACCEPTS_USER_ROLE_ACCESS=${BUSINESS_ACCEPTS_USER_ROLE_ACCESS:-PENDING}
BUSINESS_ACCEPTS_STAGING_PRODUCTS=${BUSINESS_ACCEPTS_STAGING_PRODUCTS:-PENDING}
BUSINESS_ACCEPTS_OEM_FIELD=${BUSINESS_ACCEPTS_OEM_FIELD:-PENDING}
BUSINESS_ACCEPTS_EQUIVALENT_FIELD=${BUSINESS_ACCEPTS_EQUIVALENT_FIELD:-PENDING}
BUSINESS_ACCEPTS_VEHICLE_FITMENT_FIELD=${BUSINESS_ACCEPTS_VEHICLE_FITMENT_FIELD:-PENDING}
BUSINESS_ACCEPTS_BARCODE_NON_BLOCKER=${BUSINESS_ACCEPTS_BARCODE_NON_BLOCKER:-PENDING}
BUSINESS_ACCEPTS_MARKETPLACE_PHASE_4D=${BUSINESS_ACCEPTS_MARKETPLACE_PHASE_4D:-PENDING}

---

## 3. Guard sonucu

MISSING_FIELD_COUNT=$MISSING_FIELD_COUNT
PENDING_FIELD_COUNT=$PENDING_FIELD_COUNT
INVALID_FIELD_COUNT=$INVALID_FIELD_COUNT

MISSING_FIELDS=$MISSING_FIELDS
PENDING_FIELDS=$PENDING_FIELDS
INVALID_FIELDS=$INVALID_FIELDS

BLOCKER_REASON=$BLOCKER_REASON

---

## 4. Final status

4C_6G_2_BUSINESS_ACCEPTANCE_APPLY_STATUS=$ACCEPTANCE_APPLY_STATUS
4C_6G_2_BUSINESS_ACCEPTANCE_GATE_STATUS=$BUSINESS_ACCEPTANCE_GATE_STATUS
4C_6G_2_BUSINESS_ACCEPTANCE_STATUS=${BUSINESS_ACCEPTANCE_STATUS:-PENDING}
4C_6G_2_FINAL_UAT_RESULT=$FINAL_UAT_RESULT
4C_6G_2_GO_NO_GO_READY=$GO_NO_GO_READY
4C_6G_2_MISSING_FIELD_COUNT=$MISSING_FIELD_COUNT
4C_6G_2_PENDING_FIELD_COUNT=$PENDING_FIELD_COUNT
4C_6G_2_INVALID_FIELD_COUNT=$INVALID_FIELD_COUNT
4C_6G_2_BLOCKER_REASON=$BLOCKER_REASON
4C_6G_2_DB_WRITE_APPLIED=NO
4C_6G_2_CRITICAL_BLOCKER_COUNT=$CRITICAL_BLOCKER_COUNT
4C_6G_2_WARNING_COUNT=$WARNING_COUNT
4C_6H_READY=$NEXT_READY
DOC_EOF

cat > "$REPORT_FILE" <<REPORT_EOF
# FAZ 4C — 4C-6G-2 Business Acceptance Apply Report

Step: 4C-6G-2
Blok: Business Acceptance Apply / Gate Finalization
Test tarihi: $(date '+%Y-%m-%d %H:%M:%S')

## Test sonucu

4C_6G_2_BUSINESS_ACCEPTANCE_APPLY_STATUS=$ACCEPTANCE_APPLY_STATUS
4C_6G_2_BUSINESS_ACCEPTANCE_GATE_STATUS=$BUSINESS_ACCEPTANCE_GATE_STATUS
4C_6G_2_BUSINESS_ACCEPTANCE_STATUS=${BUSINESS_ACCEPTANCE_STATUS:-PENDING}
4C_6G_2_BUSINESS_REPRESENTATIVE_NAME=${BUSINESS_REPRESENTATIVE_NAME:-PENDING}
4C_6G_2_BUSINESS_ACCEPTANCE_DATE=${BUSINESS_ACCEPTANCE_DATE:-PENDING}
4C_6G_2_FINAL_UAT_RESULT=$FINAL_UAT_RESULT
4C_6G_2_GO_NO_GO_READY=$GO_NO_GO_READY
4C_6G_2_MISSING_FIELD_COUNT=$MISSING_FIELD_COUNT
4C_6G_2_PENDING_FIELD_COUNT=$PENDING_FIELD_COUNT
4C_6G_2_INVALID_FIELD_COUNT=$INVALID_FIELD_COUNT
4C_6G_2_BLOCKER_REASON=$BLOCKER_REASON
4C_6G_2_DB_WRITE_APPLIED=NO
4C_6G_2_CRITICAL_BLOCKER_COUNT=$CRITICAL_BLOCKER_COUNT
4C_6G_2_WARNING_COUNT=$WARNING_COUNT
4C_6H_READY=$NEXT_READY

## Pending fields

$PENDING_FIELDS

## Missing fields

$MISSING_FIELDS

## Invalid fields

$INVALID_FIELDS

## Karar

Business acceptance gate sonucu: $BUSINESS_ACCEPTANCE_GATE_STATUS
Final UAT result: $FINAL_UAT_RESULT
Go / No-Go ready: $GO_NO_GO_READY

## Sonuc

Business acceptance apply guard çalıştı.
Bu adımda DB yazma işlemi yapılmadı.
REPORT_EOF

echo "OK ✅ Business acceptance apply dokumani olusturuldu: $DOC_FILE"
echo "OK ✅ Business acceptance apply report olusturuldu: $REPORT_FILE"

echo
echo "===== 4C-6G-2 APPLY OZET ====="
echo "4C_6G_2_BUSINESS_ACCEPTANCE_APPLY_STATUS=$ACCEPTANCE_APPLY_STATUS"
echo "4C_6G_2_BUSINESS_ACCEPTANCE_GATE_STATUS=$BUSINESS_ACCEPTANCE_GATE_STATUS"
echo "4C_6G_2_BUSINESS_ACCEPTANCE_STATUS=${BUSINESS_ACCEPTANCE_STATUS:-PENDING}"
echo "4C_6G_2_FINAL_UAT_RESULT=$FINAL_UAT_RESULT"
echo "4C_6G_2_GO_NO_GO_READY=$GO_NO_GO_READY"
echo "4C_6G_2_PENDING_FIELD_COUNT=$PENDING_FIELD_COUNT"
echo "4C_6G_2_BLOCKER_REASON=$BLOCKER_REASON"
echo "4C_6G_2_DB_WRITE_APPLIED=NO"
echo "4C_6H_READY=$NEXT_READY"
