#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

PREV_REPORT="reports/pilot/faz4c/4c_8a_go_no_go_criteria_report.md"
INPUT_ENV="docs/pilot/faz4c/4c_8a_go_no_go_decision_input.env"
DECISION_FORM="uat/pilot/faz4c/uzmanparcaci/go_no_go_decision_form.md"

DOC_FILE="docs/pilot/faz4c/4c_8b_go_no_go_decision_apply.md"
REPORT_FILE="reports/pilot/faz4c/4c_8b_go_no_go_decision_apply_report.md"

echo "===== 4C-8B GO / NO-GO DECISION APPLY GUARD ====="

fail() {
  echo "HATA ❌ $1"
  exit 1
}

[ -f "$PREV_REPORT" ] || fail "4C-8A report yok: $PREV_REPORT"
[ -f "$INPUT_ENV" ] || fail "Decision input env yok: $INPUT_ENV"
[ -f "$DECISION_FORM" ] || fail "Decision form yok: $DECISION_FORM"

grep -q "4C_8A_GO_NO_GO_CRITERIA_STATUS=PASS" "$PREV_REPORT" || fail "4C-8A criteria PASS degil"
grep -q "4C_8A_SYSTEM_RECOMMENDATION=GO" "$PREV_REPORT" || fail "4C-8A system recommendation GO degil"
grep -q "4C_8B_READY=YES" "$PREV_REPORT" || fail "4C-8B ready YES yok"

# shellcheck disable=SC1090
source "$INPUT_ENV"

required_keys=(
  FINAL_GO_NO_GO_DECISION
  DECISION_OWNER
  DECISION_DATE
  DECISION_NOTE
  ACCEPTS_PHASE_4D_CARRY_FORWARD
  ACCEPTS_MARKETPLACE_PHASE_4D
  ACCEPTS_NO_CORE_PRODUCT_APPLY_IN_4C
  ACCEPTS_NO_LIVE_MARKETPLACE_IN_4C
)

yes_no_keys=(
  ACCEPTS_PHASE_4D_CARRY_FORWARD
  ACCEPTS_MARKETPLACE_PHASE_4D
  ACCEPTS_NO_CORE_PRODUCT_APPLY_IN_4C
  ACCEPTS_NO_LIVE_MARKETPLACE_IN_4C
)

MISSING_FIELD_COUNT=0
PENDING_FIELD_COUNT=0
INVALID_FIELD_COUNT=0
MISSING_FIELDS=""
PENDING_FIELDS=""
INVALID_FIELDS=""

for key in "${required_keys[@]}"; do
  val="${!key:-__MISSING__}"

  if [ "$val" = "__MISSING__" ]; then
    MISSING_FIELD_COUNT=$((MISSING_FIELD_COUNT + 1))
    MISSING_FIELDS="${MISSING_FIELDS}${key} "
    continue
  fi

  if [ "$val" = "PENDING" ] || [ -z "$val" ]; then
    PENDING_FIELD_COUNT=$((PENDING_FIELD_COUNT + 1))
    PENDING_FIELDS="${PENDING_FIELDS}${key} "
  fi
done

case "${FINAL_GO_NO_GO_DECISION:-PENDING}" in
  GO|CONDITIONAL_GO|NO_GO|PENDING)
    ;;
  *)
    INVALID_FIELD_COUNT=$((INVALID_FIELD_COUNT + 1))
    INVALID_FIELDS="${INVALID_FIELDS}FINAL_GO_NO_GO_DECISION "
    ;;
esac

for key in "${yes_no_keys[@]}"; do
  val="${!key:-PENDING}"

  if [ "$val" = "PENDING" ]; then
    continue
  fi

  case "$val" in
    YES|NO)
      ;;
    *)
      INVALID_FIELD_COUNT=$((INVALID_FIELD_COUNT + 1))
      INVALID_FIELDS="${INVALID_FIELDS}${key} "
      ;;
  esac
done

APPLY_STATUS="PASS"
DECISION_GATE_STATUS="PASS"
FINAL_DECISION_STATUS="${FINAL_GO_NO_GO_DECISION:-PENDING}"
GO_NO_GO_FINALIZATION_READY="YES"
NEXT_READY="YES"
BLOCKER_REASON="NONE"
CRITICAL_BLOCKER_COUNT="0"
WARNING_COUNT="0"

if [ "$MISSING_FIELD_COUNT" -ne 0 ] || [ "$PENDING_FIELD_COUNT" -ne 0 ] || [ "$INVALID_FIELD_COUNT" -ne 0 ]; then
  APPLY_STATUS="BLOCKED"
  DECISION_GATE_STATUS="PENDING"
  FINAL_DECISION_STATUS="PENDING"
  GO_NO_GO_FINALIZATION_READY="NO"
  NEXT_READY="NO"
  BLOCKER_REASON="GO_NO_GO_DECISION_FIELDS_NOT_FINAL"
fi

if [ "${FINAL_GO_NO_GO_DECISION:-PENDING}" = "NO_GO" ] && [ "$APPLY_STATUS" = "PASS" ]; then
  DECISION_GATE_STATUS="NO_GO"
  FINAL_DECISION_STATUS="NO_GO"
  GO_NO_GO_FINALIZATION_READY="YES"
  NEXT_READY="YES"
  WARNING_COUNT="1"
  BLOCKER_REASON="NO_GO_DECISION_SELECTED"
fi

if [ "${FINAL_GO_NO_GO_DECISION:-PENDING}" = "CONDITIONAL_GO" ] && [ "$APPLY_STATUS" = "PASS" ]; then
  DECISION_GATE_STATUS="CONDITIONAL_GO"
  FINAL_DECISION_STATUS="CONDITIONAL_GO"
  GO_NO_GO_FINALIZATION_READY="YES"
  NEXT_READY="YES"
  WARNING_COUNT="1"
fi

if [ "${FINAL_GO_NO_GO_DECISION:-PENDING}" = "GO" ] && [ "$APPLY_STATUS" = "PASS" ]; then
  DECISION_GATE_STATUS="GO"
  FINAL_DECISION_STATUS="GO"
  GO_NO_GO_FINALIZATION_READY="YES"
  NEXT_READY="YES"
fi

cat > "$DOC_FILE" <<DOC_EOF
# FAZ 4C — 4C-8B Go / No-Go Decision Apply Guard

## Blok

4C-8B — Go / No-Go Decision Apply Guard

## Amaç

4C-8A decision input dosyasını okuyup final GO / CONDITIONAL_GO / NO_GO kararının geçerli olup olmadığını kontrol etmek.

Bu adım DB'ye yazmaz.

---

## 1. Kaynak

PREV_REPORT=$PREV_REPORT
INPUT_ENV=$INPUT_ENV
DECISION_FORM=$DECISION_FORM

---

## 2. Input değerleri

SYSTEM_RECOMMENDATION=${SYSTEM_RECOMMENDATION:-PENDING}
FINAL_GO_NO_GO_DECISION=${FINAL_GO_NO_GO_DECISION:-PENDING}
DECISION_OWNER=${DECISION_OWNER:-PENDING}
DECISION_DATE=${DECISION_DATE:-PENDING}
DECISION_NOTE=${DECISION_NOTE:-PENDING}

ACCEPTS_PHASE_4D_CARRY_FORWARD=${ACCEPTS_PHASE_4D_CARRY_FORWARD:-PENDING}
ACCEPTS_MARKETPLACE_PHASE_4D=${ACCEPTS_MARKETPLACE_PHASE_4D:-PENDING}
ACCEPTS_NO_CORE_PRODUCT_APPLY_IN_4C=${ACCEPTS_NO_CORE_PRODUCT_APPLY_IN_4C:-PENDING}
ACCEPTS_NO_LIVE_MARKETPLACE_IN_4C=${ACCEPTS_NO_LIVE_MARKETPLACE_IN_4C:-PENDING}

---

## 3. Guard sonucu

MISSING_FIELD_COUNT=$MISSING_FIELD_COUNT
PENDING_FIELD_COUNT=$PENDING_FIELD_COUNT
INVALID_FIELD_COUNT=$INVALID_FIELD_COUNT

MISSING_FIELDS=$MISSING_FIELDS
PENDING_FIELDS=$PENDING_FIELDS
INVALID_FIELDS=$INVALID_FIELDS

BLOCKER_REASON=$BLOCKER_REASON

---

## 4. Final status

4C_8B_GO_NO_GO_DECISION_APPLY_STATUS=$APPLY_STATUS
4C_8B_DECISION_GATE_STATUS=$DECISION_GATE_STATUS
4C_8B_SYSTEM_RECOMMENDATION=${SYSTEM_RECOMMENDATION:-PENDING}
4C_8B_FINAL_GO_NO_GO_DECISION=$FINAL_DECISION_STATUS
4C_8B_GO_NO_GO_FINALIZATION_READY=$GO_NO_GO_FINALIZATION_READY
4C_8B_MISSING_FIELD_COUNT=$MISSING_FIELD_COUNT
4C_8B_PENDING_FIELD_COUNT=$PENDING_FIELD_COUNT
4C_8B_INVALID_FIELD_COUNT=$INVALID_FIELD_COUNT
4C_8B_BLOCKER_REASON=$BLOCKER_REASON
4C_8B_DB_WRITE_APPLIED=NO
4C_8B_CRITICAL_BLOCKER_COUNT=$CRITICAL_BLOCKER_COUNT
4C_8B_WARNING_COUNT=$WARNING_COUNT
4C_8C_READY=$NEXT_READY
DOC_EOF

cat > "$REPORT_FILE" <<REPORT_EOF
# FAZ 4C — 4C-8B Go / No-Go Decision Apply Report

Step: 4C-8B
Blok: Go / No-Go Decision Apply Guard
Test tarihi: $(date '+%Y-%m-%d %H:%M:%S')

## Test sonucu

4C_8B_GO_NO_GO_DECISION_APPLY_STATUS=$APPLY_STATUS
4C_8B_DECISION_GATE_STATUS=$DECISION_GATE_STATUS
4C_8B_SYSTEM_RECOMMENDATION=${SYSTEM_RECOMMENDATION:-PENDING}
4C_8B_FINAL_GO_NO_GO_DECISION=$FINAL_DECISION_STATUS
4C_8B_DECISION_OWNER=${DECISION_OWNER:-PENDING}
4C_8B_DECISION_DATE=${DECISION_DATE:-PENDING}
4C_8B_GO_NO_GO_FINALIZATION_READY=$GO_NO_GO_FINALIZATION_READY
4C_8B_MISSING_FIELD_COUNT=$MISSING_FIELD_COUNT
4C_8B_PENDING_FIELD_COUNT=$PENDING_FIELD_COUNT
4C_8B_INVALID_FIELD_COUNT=$INVALID_FIELD_COUNT
4C_8B_BLOCKER_REASON=$BLOCKER_REASON
4C_8B_DB_WRITE_APPLIED=NO
4C_8B_CRITICAL_BLOCKER_COUNT=$CRITICAL_BLOCKER_COUNT
4C_8B_WARNING_COUNT=$WARNING_COUNT
4C_8C_READY=$NEXT_READY

## Pending fields

$PENDING_FIELDS

## Missing fields

$MISSING_FIELDS

## Invalid fields

$INVALID_FIELDS

## Karar

Decision gate status: $DECISION_GATE_STATUS
Final decision: $FINAL_DECISION_STATUS
Finalization ready: $GO_NO_GO_FINALIZATION_READY

## Sonuc

Go / No-Go decision apply guard çalıştı.
Bu adımda DB yazma işlemi yapılmadı.
REPORT_EOF

echo "OK ✅ Go / No-Go apply dokumani olusturuldu: $DOC_FILE"
echo "OK ✅ Go / No-Go apply report olusturuldu: $REPORT_FILE"

echo
echo "===== 4C-8B APPLY OZET ====="
echo "4C_8B_GO_NO_GO_DECISION_APPLY_STATUS=$APPLY_STATUS"
echo "4C_8B_DECISION_GATE_STATUS=$DECISION_GATE_STATUS"
echo "4C_8B_SYSTEM_RECOMMENDATION=${SYSTEM_RECOMMENDATION:-PENDING}"
echo "4C_8B_FINAL_GO_NO_GO_DECISION=$FINAL_DECISION_STATUS"
echo "4C_8B_GO_NO_GO_FINALIZATION_READY=$GO_NO_GO_FINALIZATION_READY"
echo "4C_8B_PENDING_FIELD_COUNT=$PENDING_FIELD_COUNT"
echo "4C_8B_BLOCKER_REASON=$BLOCKER_REASON"
echo "4C_8B_DB_WRITE_APPLIED=NO"
echo "4C_8C_READY=$NEXT_READY"
