#!/usr/bin/env bash
set -euo pipefail

echo "===== 15.6 MATERIALIZED VIEW / CACHE PROJECTION CANDIDATE EXECUTION PLAN ====="

APPLY_MATERIALIZED_CACHE="${APPLY_MATERIALIZED_CACHE:-0}"
PROJECTION_KEY="${PROJECTION_KEY:-}"
TENANT_ID="${TENANT_ID:-}"
DRY_RUN="${DRY_RUN:-1}"

echo "DB_MUTATION=NO"
echo "REDIS_MUTATION=NO"
echo "MATERIALIZED_VIEW_REFRESH_EXECUTED=NO"
echo "CACHE_WRITE_EXECUTED=NO"
echo "QUERY_TEXT_PRINTED=NO"

if [ "$APPLY_MATERIALIZED_CACHE" != "1" ]; then
  echo "MATERIALIZED_CACHE_PLAN_BLOCKED_BY_DEFAULT=YES"
  echo "MATERIALIZED_CACHE_PLAN_DECISION=PLAN_READY_APPLY_NOT_EXECUTED"
  exit 0
fi

echo "MATERIALIZED_CACHE_PLAN_BLOCKED_BY_DEFAULT=YES"
echo "MATERIALIZED_CACHE_PLAN_DECISION=REFUSED_IN_15_6_STANDARD_STEP"
echo "ERROR: 15.6 standard adiminda gercek materialized view refresh veya cache write calistirilmaz."
echo "ERROR: Controlled apply gate olmadan DB/Redis mutation yapilmaz."
exit 2
