#!/usr/bin/env bash
set -Eeuo pipefail

REPO="${REPO:-$HOME/pix2pi/pix2pi-SaaS}"
cd "$REPO"

EVIDENCE_DIR="docs/faz7r/evidence"
CONFIG_DIR="configs/faz7r"
GUARD_FILE="scripts/faz7r/faz7r_real_pass_guard.sh"
REPORT_FILE="${EVIDENCE_DIR}/FAZ_7R_361_3_PARTIAL_PASS_RECLASSIFICATION.tsv"
SUMMARY_FILE="${EVIDENCE_DIR}/FAZ_7R_361_3_PASS_RULE_SUMMARY.env"

test -f "$GUARD_FILE"
# shellcheck source=/dev/null
source "$GUARD_FILE"

mkdir -p "$EVIDENCE_DIR"

SCANNED_EVIDENCE_FILE_COUNT=0
SCANNED_CONFIG_FILE_COUNT=0
OLD_PASS_FILE_COUNT=0
PARTIAL_MARKER_FILE_COUNT=0
INVALID_PARTIAL_PASS_COUNT=0
PARTIAL_MARKER_NO_PASS_COUNT=0
OLD_PASS_NO_FORBIDDEN_MARKER_COUNT=0

printf "file\tclassification\treason\tfirst_marker\n" > "$REPORT_FILE"

if compgen -G "${EVIDENCE_DIR}/*.md" >/dev/null; then
  while IFS= read -r -d '' file; do
    SCANNED_EVIDENCE_FILE_COUNT=$((SCANNED_EVIDENCE_FILE_COUNT + 1))

    set +e
    line="$(faz7r_scan_evidence_file "$file")"
    code="$?"
    set -e

    if [[ -n "$line" ]]; then
      printf "%s\n" "$line" >> "$REPORT_FILE"
    fi

    case "$line" in
      *$'\t'"INVALID_PARTIAL_PASS"$'\t'*)
        INVALID_PARTIAL_PASS_COUNT=$((INVALID_PARTIAL_PASS_COUNT + 1))
        OLD_PASS_FILE_COUNT=$((OLD_PASS_FILE_COUNT + 1))
        PARTIAL_MARKER_FILE_COUNT=$((PARTIAL_MARKER_FILE_COUNT + 1))
        ;;
      *$'\t'"OLD_PASS_NO_FORBIDDEN_MARKER_FOUND"$'\t'*)
        OLD_PASS_NO_FORBIDDEN_MARKER_COUNT=$((OLD_PASS_NO_FORBIDDEN_MARKER_COUNT + 1))
        OLD_PASS_FILE_COUNT=$((OLD_PASS_FILE_COUNT + 1))
        ;;
      *$'\t'"PARTIAL_MARKER_NO_PASS"$'\t'*)
        PARTIAL_MARKER_NO_PASS_COUNT=$((PARTIAL_MARKER_NO_PASS_COUNT + 1))
        PARTIAL_MARKER_FILE_COUNT=$((PARTIAL_MARKER_FILE_COUNT + 1))
        ;;
    esac

    true
  done < <(find "$EVIDENCE_DIR" -maxdepth 1 -type f -name '*.md' ! -name 'FAZ_7R_361_3_AUDIT_SAYACLARI_PASS_KURALI_DUZELTMESI_AUDIT.md' -print0 | sort -z)
fi

if compgen -G "${CONFIG_DIR}/*.json" >/dev/null; then
  while IFS= read -r -d '' file; do
    SCANNED_CONFIG_FILE_COUNT=$((SCANNED_CONFIG_FILE_COUNT + 1))
  done < <(find "$CONFIG_DIR" -maxdepth 1 -type f -name '*.json' -print0 | sort -z)
fi

if [[ "$INVALID_PARTIAL_PASS_COUNT" -gt 0 ]]; then
  FAZ_7R_FINAL_CLOSURE_ALLOWED="NO"
  FAZ_7R_PARTIAL_PASS_RECLASSIFICATION_REQUIRED="YES"
else
  FAZ_7R_FINAL_CLOSURE_ALLOWED="YES"
  FAZ_7R_PARTIAL_PASS_RECLASSIFICATION_REQUIRED="NO"
fi

cat > "$SUMMARY_FILE" <<SUMMARY
SCANNED_EVIDENCE_FILE_COUNT=${SCANNED_EVIDENCE_FILE_COUNT}
SCANNED_CONFIG_FILE_COUNT=${SCANNED_CONFIG_FILE_COUNT}
OLD_PASS_FILE_COUNT=${OLD_PASS_FILE_COUNT}
PARTIAL_MARKER_FILE_COUNT=${PARTIAL_MARKER_FILE_COUNT}
INVALID_PARTIAL_PASS_COUNT=${INVALID_PARTIAL_PASS_COUNT}
PARTIAL_MARKER_NO_PASS_COUNT=${PARTIAL_MARKER_NO_PASS_COUNT}
OLD_PASS_NO_FORBIDDEN_MARKER_COUNT=${OLD_PASS_NO_FORBIDDEN_MARKER_COUNT}
FAZ_7R_PARTIAL_PASS_RECLASSIFICATION_REQUIRED=${FAZ_7R_PARTIAL_PASS_RECLASSIFICATION_REQUIRED}
FAZ_7R_FINAL_CLOSURE_ALLOWED=${FAZ_7R_FINAL_CLOSURE_ALLOWED}
FAZ_7R_317_3_READY=YES
SUMMARY

cat "$SUMMARY_FILE"
