proxy_intercept_errors on;

error_page 400 401 403 404 /__pix2pi_error_minimal__.html;
error_page 500 502 503 504 /__pix2pi_error_minimal__.html;

location = /__pix2pi_error_minimal__.html {
    internal;
    default_type text/html;
    return 200 '<html><body><h1>Request could not be completed.</h1></body></html>';
}
