package repository

// Page defaults are part of the reporting contract from FAZ 4 / 16.1.
const (
	DefaultLimit = 50
	MaxLimit     = 200
)

// PageRequest describes opaque cursor pagination for readmodel queries.
type PageRequest struct {
	Limit  int
	Cursor string
}

// QuerySpec is a read-only query contract generated by the repository layer.
// It is intentionally separated from HTTP handlers and runtime execution.
type QuerySpec struct {
	Name        string
	SourceTable string
	SQL         string
	Args        []any
	Limit       int
	ReadOnly    bool
}

// DailyMetricsFilter filters readmodel.daily_operational_metrics.
type DailyMetricsFilter struct {
	TenantID string
	FromDate string
	ToDate   string
	Page     PageRequest
}

// InventoryStatusFilter filters readmodel.inventory_status_snapshot.
type InventoryStatusFilter struct {
	TenantID    string
	WarehouseID string
	SKU         string
	AlertOnly   *bool
	Page        PageRequest
}

// DocumentWorkQueueFilter filters readmodel.document_work_queue.
type DocumentWorkQueueFilter struct {
	TenantID     string
	DocumentType string
	SourceModule string
	Status       string
	PriorityLTE  *int
	Page         PageRequest
}

// ReconciliationStatusFilter filters readmodel.reconciliation_status_snapshot.
type ReconciliationStatusFilter struct {
	TenantID     string
	ScopeType    string
	Status       string
	CurrencyCode string
	Page         PageRequest
}

// ProjectionStateFilter filters readmodel.projection_state.
type ProjectionStateFilter struct {
	TenantID       string
	ProjectionName string
	Status         string
	Page           PageRequest
}
